### ISSUE TITLE
Now can I get smart things to recognize my doorbell

### ISSUE THREAD

**Issue by bob5731** [jsetton/smartthings-ring#15]
It keeps asking me to choose a doorbell.
I picked the ring doorbell then it asked me to pick it again.

I've also created a device in the IDE with no luck.
Got it to recognize it once went into the IDE to clean up multiple ring devices and excellent deleted the wrong one

**Comment by jsetton** [comment]
> I've also created a device in the IDE with no luck.

Valid devices can only be created using the SmartApp.

With the migration to the new Smartthings app and the announced plan for Samsung to deprecate the current IDE platform by the end of the year, I expect my current implementation to break if not already. Once it becomes more clear what the current platform is being replaced with, I will try to update it.

Until then, I strongly recommend using the official Ring integration. Anyway, the main goal I had in mind when I developed these device handlers was to control the siren on products that supports that feature since the official device handlers don't provide that control. All other features are present in the official integration.

**Comment by bob5731** [comment]
The problem I have is smart things and ring don't support the ring video doorbell too. You're up finally recognize my doorbell but with no video.

**Comment by jsetton** [comment]
> but with no video

As mentioned in the readme overview, only motion/doorbell events and lights/siren controls are supported.

Unfortunately, the video feature cannot be easily implemented due to Ring closed API.
